if (${EditorBuild})
    add_compile_definitions(LMC_EDITOR)
    add_compile_definitions(HOT_RELOAD)
    add_compile_definitions(LMC_API_EXPORTS)
    add_compile_definitions("PrimaryWindow=EditorWindow")
    add_compile_definitions("RootConceptTy=DynamicConcept")
    add_compile_definitions("RootConceptIncludePath=\"Engine/Core/Runtime/DynamicLibrary/DynamicConcept.hpp\"")
else ()
    add_compile_definitions(LMC_API_STATIC)
    add_compile_definitions("PrimaryWindow=GameWindow")
    add_compile_definitions("RootConceptTy=${ROOT_CONCEPT_CLASS}")
    add_compile_definitions("RootConceptIncludePath=\"${ROOT_CONCEPT_PATH}\"")
endif ()

add_compile_definitions("CMAKE_BUILD_TYPE=\"${CMAKE_BUILD_TYPE}\"")
