file(GLOB sources_list LIST_DIRECTORIES true ${CMAKE_SOURCE_DIR}/Source/*)
foreach (dir ${sources_list})
    IF (IS_DIRECTORY ${dir})
        if (EXISTS "${dir}/Public")
            message("include_directories ${dir}/Public")
            include_directories("${dir}/Public")
        endif ()
        if (EXISTS "${dir}/CmakeLists.txt")
            message("add_subdirectory ${dir}")
            add_subdirectory("${dir}")
        endif ()
    ELSE ()
        CONTINUE()
    ENDIF ()
endforeach ()